#!/bin/bash
# Generates chart/codespaces.yaml, a Helm values override that points the
# ingress at this Codespace's forwarded-port URL instead of unguard.kube.
# Run this BEFORE `skaffold run -p codespaces` / `skaffold dev -p codespaces`.
#
# chart/codespaces.yaml is generated (not committed) because the hostname is
# unique per Codespace — see .gitignore.
set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

if [[ -z "$CODESPACE_NAME" ]]; then
  echo "❌ CODESPACE_NAME is not set — this script is only meaningful inside a GitHub Codespace." >&2
  echo "   For local Kind clusters, skip this and use the default 'unguard.kube' host instead." >&2
  exit 1
fi

CODESPACE_HOST="${CODESPACE_NAME}-80.app.github.dev"

cat > "$SCRIPT_DIR/codespaces.yaml" <<EOF
# Generated by chart/generate-codespaces-values.sh — do not edit by hand, do not commit.
ingress:
  host: ${CODESPACE_HOST}
EOF

echo "✅ chart/codespaces.yaml generated."
echo "   Ingress host: ${CODESPACE_HOST}"
echo "   Once deployed, visit: https://${CODESPACE_HOST}"
